from fastapi import APIRouter, Depends, Query, Response, status

from app.core.dependency_injection import get_report_service
from app.core.exceptions import RepoMindException
from app.models.report import ReportResponse
from app.services.report_service import ReportService

router = APIRouter(prefix="/analysis", tags=["Reports"])


@router.get("/{run_id}/report", response_model=ReportResponse, status_code=status.HTTP_200_OK)
async def get_final_report(
    run_id: str,
    report_service: ReportService = Depends(get_report_service),
):
    """
    Retrieve the final consolidated report generated by Report Generator agent per API.md.
    """
    return await report_service.get_report(run_id)


@router.get("/{run_id}/report/export", status_code=status.HTTP_200_OK)
async def export_final_report(
    run_id: str,
    format: str = Query("md", description="Export format (md | pdf)"),
    report_service: ReportService = Depends(get_report_service),
):
    """
    Export final report as downloadable file per API.md.
    """
    fmt_lower = format.lower()
    if fmt_lower not in ["md", "pdf"]:
        raise RepoMindException("Unsupported export format. Must be 'md' or 'pdf'.", code="UNSUPPORTED_FORMAT", status_code=400)

    report_res = await report_service.get_report(run_id)
    content = report_res.report_markdown

    if fmt_lower == "md":
        return Response(
            content=content.encode("utf-8"),
            media_type="text/markdown",
            headers={"Content-Disposition": f'attachment; filename="repomind-report-{run_id}.md"'},
        )
    else:
        # PDF format placeholder bytes per API.md specs
        pdf_bytes = f"%PDF-1.4 Header\n{content}".encode("utf-8")
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="repomind-report-{run_id}.pdf"'},
        )
